# nginx.conf
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Upstream for backend
    upstream backend {
        server backend:5000;
    }

    # Upstream for frontend
    upstream frontend {
        server frontend:3000;
    }

    # Proxy configurations
    server {
        listen 80;

        # Serve .well-known/acme-challenge/ directory for Certbot
        location /.well-known/acme-challenge/ {
            root /var/www/html;
            try_files $uri =404;
        }

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # SSL configuration
    server {
        listen 443 ssl;
        server_name waqasdev.online;

        ssl_certificate /etc/letsencrypt/live/waqasdev.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/waqasdev.online/privkey.pem;

        # Proxy configurations
        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name waqasdev.online;
        return 301 https://$host$request_uri;
    }
}
